# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: ror_api_dev

test:
  <<: *default
  database: ror_api_test

production:
  <<: *default
  database: ror_api_prod
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>